### ISSUE TITLE
feat: 채팅 basic 코드 구현 

### ISSUE THREAD

**Issue by mjj111** [4Ailen/backend#15]
## 📄 이슈 내용

> 채팅방 생성과 대화가 가능하지만, 1대1채팅방을 자동적으로 만들어주는 서비스 로직 필요 

## ✅ 체크리스트
- [ ] redis pub/sub 사용 
- [ ] stomp 사용 
- [ ] 1대1 채팅을 기본으로 많은 채팅방 생성 가능하도록 구현

**Comment by coke98** [comment]
고생하셨습니다~
