### ISSUE TITLE
feat: 기존 채팅방 코드 삭제하기

### ISSUE THREAD

**Issue by coke98** [4Ailen/backend#40]
## 📄 이슈 내용

>
#15 에서 구현된 코드 중 현재 불필요한 코드가 많습니다.
필요한 기능을 제외하고 삭제, 정리해야할 듯 합니다.. 

## ✅ 체크리스트
- [x] 코드 삭제하기
- [x] 채팅 기능 동작에 문제없는지 확인하기
- [x] 필요 없는 주석도 삭제하기

**Comment by mjj111** [comment]
#104  에 위 이슈 내용들을 해결 했습니다.
